apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kv-{{ .Release.Name }}
spec:
  provider: azure
  parameters:
    usePodIdentity: "{{ if .Values.identity.useWorkloadIdentity }}false{{ else }}true{{ end }}"
    useVMManagedIdentity: "false"
    clientID: "{{ .Values.identity.clientId }}"
    keyvaultName: "{{ .Values.keyVault.name }}"
    tenantId: "{{ .Values.keyVault.tenantId }}"
    objects: |
      array:
        {{- range .Values.keyVault.secrets }}
        - |
          objectName: {{ .name }}
          objectType: {{ .type }}
          objectVersion: {{ .version }}
        {{- end }}
