apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  labels:
    azure.workload.identity/use: "true"
  annotations:
    azure.workload.identity/client-id: "{{ .Values.identity.clientId }}"
