replicaCount: 2

image:
  repository: restuarantsacr.azurecr.io/restaurant-service
  tag: "latest"
  pullPolicy: IfNotPresent

keyVault:
  name: restaurantsdb-kv
  tenantId: <your-tenant-id>
  secrets:
    - name: CosmosEndpoint
      type: secret
      version: "" # Optional, defaults to the latest

identity:
  clientId: <user-assigned-identity-clientid>
  useWorkloadIdentity: true

serviceAccount:
  name: workload-identity-sa

service:
  type: LoadBalancer
  port: 80
  targetPort: 6379

nodeSelector:
  kubernetes.io/os: linux
