name: 'Validate PR title'

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

jobs:
  main:
    name: Validate PR title
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
      statuses: write
    steps:
      # Please look up the latest version from
      # https://github.com/amannn/action-semantic-pull-request/releases
      - uses: amannn/action-semantic-pull-request@v5.4.0
        id: validate
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Write Summary on Failure
        if: failure()
        run: |
          echo "### Validation Summary" >> $GITHUB_STEP_SUMMARY
          echo "- **Validate**: PR Title doesn't match conventional commit scheme!" >> $GITHUB_STEP_SUMMARY
